app:
  hotels:
    events:
      topic: hotel.events

spring:
  application:
    name: staywise

  cloud:
    function:
      definition: consumeHotelEvents
    stream:
      bindings:
        consumeHotelEvents-in-0:
          destination: hotel.events
          group: hotel-service
          content-type: application/json
        produceHotelEvents-out-0:
          destination: hotel.events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/staywise
    username: postgres
    password: postgres

  elasticsearch:
    uris: http://localhost:9200

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    url: /openapi.yaml